### ISSUE TITLE
请教一下，挤地铁公交1小时看书不会累吗？

### ISSUE THREAD

**Issue by hoochanlon** [songleo/songleo.github.io#1]
真是有缘有幸在网上翻阅多次，搜翻到你的文章 [我的阅读时间](http://reborncodinglife.com/2019/01/19/about-my-reading-time/)。不过我有个疑惑：

我之前上班特别是挤公交来回1小时很疲惫，只看得下知乎热点及影评之类快餐文章...我坐公交看书有种脑袋沉沉的感觉。

**Comment by songleo** [comment]
@hoochanlon 抱歉，回复太晚了，主要是看个人习惯，习惯了就好了，我一坐车就喜欢微信读书。不过最近1年有小孩了，看书少了，最近才慢慢恢复，尴尬了：）
